name: MadelynnLand
favicon: null
layout_spectrum: 0.25207
typography_spectrum: 0.3456998
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc421b'
    - '#7a2c13'
    - '#a77a48'
    - '#5aa7d7'
  brandStrength: 1
  lightness: 0.3311129049398005
  saturation: 0.6547243287786841
  rhythmicContrast: 0.2965197144076228
purpose: []
